# This is a basic workflow to help you get started with Actions

name: main

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# * * * * *  command to execute
# ┬ ┬ ┬ ┬ ┬
# │ │ │ │ └───── day of week (0 - 7) (0 to 6 are Sunday to Saturday, or use names; 7 is Sunday, the same as 0)
# │ │ │ └────────── month (1 - 12)
# │ │ └─────────────── day of month (1 - 31)
# │ └──────────────────── hour (0 - 23)
# └───────────────────────── min (0 - 59)
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '59 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install R Package (multi-line script)
    - uses: r-lib/actions/setup-r@v1
    - name: Install Package Dependencies
      env:
        GITHUB_PAT: ${{ secrets.GIT_TOKEN }}
      run: |-
        Rscript -e "install.packages('remotes')"
        Rscript -e "install.packages('devtools')"
        Rscript -e "devtools::install_github('gadenbuie/tweetrmd', ref='main')"
        Rscript -e "remotes::install_github('rstudio/webshot2', ref='main')"
        Rscript -e "install.packages('rtweet')"  

    # Generate Twitter Image
    - name: Generate Twitter Image
      env:
        ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      run: |-
        Rscript script.R

    # Update git repository
    - name: Commit and push if changed
      run: |-
        git add .
        git diff
        git config --global user.email "github-action-bot@example.com"
        git config --global user.name "GitHub Action Bot"
        git commit -m "Updated tweet.png" -a || echo "No changes to commit"
        git push        
